# Generated by Django 2.2.1 on 2020-02-26 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0005_auto_20200226_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='goods_status',
            field=models.IntegerField(default=1, verbose_name='商品状态'),
        ),
    ]
