# Generated by Django 2.2.1 on 2020-02-26 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Seller', '0007_auto_20200226_2022'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='goods_description',
            field=models.TextField(default='好吃', verbose_name='商品的描述'),
        ),
    ]
